GeoNode/documentation

- admin/mgmt_commands/index.rst
Management command `delete_resources` description
> delete_resources description

- intermediate/backup/index.rst
Restore notification argument description
> restore notification

- admin/admin_panel/index.rst
Describe changes in advanced publish workflow
> FIX #5990 additional description in advance publish workflow

- install/core/index.rst
Since I installed the `GeoNode` recently. I am trying to help the other people who want to install the GeoNode locally and do some tests on window before directly move to production mode. Please update the documentation for windows installation also. Later I am planning to add how to connect the `Postgres` database in this section.
> Windows installation for development mode only

- install/core/index.rst
The documentation of the windows installation updated. The PostgreSQL database connection for the GeoNode added. I tested in my windows machine this code. This will be helpful for Windows users.
> Windows installation: postgresql connection

- install/core/index.rst
The apache-tomcat version specified there (`8.5.53`) generate the 404 error. It needs to be changed to `8.5.55`
> version of apache-tomcat updated

- advanced/contrib/index.rst
- devel/installation/index.rst
- install/advanced/core/index.rst
- install/advanced/project/index.rst
- install/basic/index.rst
Reverts GeoNode/documentation#41
> Revert "[Issue GeoNode/geonode#6079] Reference spatial data stores for Django database"

- intermediate/backup/index.rst
the build server is down. as we kindly can use geosolutions I've set that one.
> Fixes #58 404 with build.geonode.org

- install/advanced/core/index.rst
Added installation information for RedHat EL 7.x
> RHEL installation

- install/advanced/core/docker/centos.rst
- install/advanced/core/docker/ubuntu.rst
- install/advanced/core/index.rst
This small section on "Core Setup" describes in details what docker does in order to fully enable asynchronous workers
Few screenshots below
>  - How to setup rabbitmq, supervisor and memcached in order to fully enable async workers

- admin/upgrade/index.rst
This small section on "Upgrade" describes how to migrate from an old 3.0 version
Few screenshots below
>  - How to Upgrade from 2.10.x / 3.0

- basic/settings/index.rst
With this PR i want to:
- add information for the new settings `CATALOG_METADATA_TEMPLATE` for the `geonode` core project 
Links:
[Issue ](https://github.com/GeoNode/geonode/issues/6899)
[PR](https://github.com/GeoNode/geonode/pull/6894)
> [Fixes #6899]Documentantion for new metadata settings

- basic/settings/index.rst
add documentantion for uuidhandler
- issue: [#6952](https://github.com/GeoNode/geonode/issues/6952)
- PR: [#6953](https://github.com/GeoNode/geonode/pull/6953)
> Refers #6952: add documentantion for uuidhandler

- basic/settings/index.rst
Documentation about https://github.com/GeoNode/geonode/issues/7097
> [Fixes #7097] Allow XSL customization

- admin/thesaurus/index.rst
Refers to:
Issue: https://github.com/GeoNode/geonode/issues/7214
PR: https://github.com/GeoNode/geonode/pull/7225
> [Refers to #7214] Sorting Thesauri

- basic/settings/index.rst
Documentation for ADVANCED_EDIT_EXCLUDE_FIELD
Issue:  https://github.com/GeoNode/geonode/issues/6995
PR: https://github.com/GeoNode/geonode/pull/7243
> [Relates to #6995] Documentation for ADVANCED_EDIT_EXCLUDE_FIELD

- basic/settings/index.rst
- PR: https://github.com/GeoNode/geonode/pull/7309
- GNIP: https://github.com/GeoNode/geonode/issues/7263
> [Relates to #7263] Add documentation for storers and parsers hook

- admin/async/index.rst
- api/V2/schema/openapi.yml
The idea is to improve the documentation regarding the API endpoints available in GeoNode.
I also add a part related to how to perform an async upload through API (it could be useful)
> Improve API documentation

- basic/settings/index.rst
Related issue: https://github.com/GeoNode/geonode/issues/7441
Related PR: https://github.com/GeoNode/geonode/pull/7453
> [Relates to #7441] Handle configuration for CSW pre-filtering 

- admin/mgmt_commands/index.rst
Related PR: https://github.com/GeoNode/geonode/pull/7439
Related issue: https://github.com/GeoNode/geonode/issues/7435
> [Relates to #7435] Include UUID handling in set_all_layer_metadata

- admin/mgmt_commands/index.rst
- advanced/components/index.rst
- basic/settings/index.rst
- contribute/translation/index.rst
- devel/installation/index.rst
- install/advanced/project/index.rst
- install/basic/index.rst
- Update all references to Django==3.2
- Add few info for memcache settings
Related Issue: https://github.com/GeoNode/geonode/pull/7373
Related PR: https://github.com/GeoNode/geonode/issues/7366
> [Relates to #7366] Update documentation for Django3

- install/advanced/core/index.rst
> Fix for ss command not found.

- install/advanced/core/index.rst
> update rabbitmq install to use packagecloud.io distribution #175

- basic/settings/index.rst
related to https://github.com/GeoNode/geonode/issues/8422
> [DOC_#8422] added SERVICES_TYPE_MODULES into settings doc

- .gitignore
- basic/settings/index.rst
GeoNode PR https://github.com/GeoNode/geonode/pull/8730
GeoNode ISSUE:  https://github.com/geonode/geonode/issues/8712
> [3.3.x] Add documentation for GEONODE_APPS_ENABLED

- advanced/components/index.rst
- advanced/hardening/index.rst
> [Fixes #222] Remove empty headers

- install/basic/index.rst
adds command to create an env file before starting up containers
> Update basic install docs

- .gitignore
- basic/settings/index.rst
GeoNode PR https://github.com/GeoNode/geonode/pull/8730
GeoNode ISSUE:  https://github.com/geonode/geonode/issues/8712
> [WIP - Do not merge][Master] Add documentation for GEONODE_APPS_ENABLED

- install/advanced/core/index.rst
python-certbot-nginx is no longer available
> update python certbot package name

- usage/managing_layers/layer_editing.rst
wait this [issue](https://github.com/GeoNode/geonode/issues/8905) to be merged before merging this PR
> [Fixes #227] Add condition to consider a layer replacable/updatable

- admin/admin_panel/index.rst
> [Fixes #233] Advanced Workflow: workflow logic should take precedence over standard permissions

- install/advanced/project/index.rst
> [Fixes #238] Update to advanced installation for geonode-project

- devel/api/V2/schema/openapi.yml
- devel/api/usage/index.rst
ISO-19115 compliant metadata file can be uploaded soon. Creating a draft PR to make the process a bit smoother.
> Added documentation and example for metadata upload

- install/advanced/core/index.rst
geoserver version aligned with the one used in the docker-compose
> update gs version

- basic/settings/index.rst
- usage/dashboard/index.rst
- usage/download_handlers/index.rst
- usage/index.rst
improve documentation about the download handlers
> Fixup documentation

- advanced/components/index.rst
- devel/installation/install_gdal_for_development.rst
- install/advanced/core/index.rst
- install/advanced/project/index.rst
- install/basic/index.rst
- start/quick/index.rst
Add missing geofence configuration in advanced installation
> Fix Geoserver configuration since Geofence with H2 is not supported by default aynmore
