GeoNode/documentation

install/core/index.rst

Hi, 
This PR contains just a small patch to fix typo in the installation instructions:
- Word typo `envioroment`
- Tomcat version from `8.5.50` to `8.5.53` in the script

[Fix  #24] Small typo in GeoNode Core Installation

---

contribute/documentation/index.rst
contribute/index.rst
contribute/participate_discussion/index.rst

This is a part for #10 -> writing documentation, conrtibute
- Explanations copied from branch 2.6, shortened and a bit extended (sphinx dev server)
- merged discussion and github issues under one page
> not perfect but maybe better than nothing ;)

#10 Add docs for docs

---

advanced/contrib/index.rst

As we already use os.getenv I do not see the need to introduce another way of reading env variables. Further following the current docs one would need to install a package like 'envs` first ...

Suggest the use of os.getenv over env()

---

advanced/contrib/index.rst
devel/installation/index.rst
install/advanced/core/index.rst
install/advanced/project/index.rst
install/basic/index.rst

PR to change URLs and references to Postgres and SQLite databases to PostGIS and Spatialite databases respectively, where appropriate. This change is part of the greater [GNIP 75 - Enable spatial data store for Django DB](https://github.com/GeoNode/geonode/issues/6079).

[Issue GeoNode/geonode#6079] Reference spatial data stores for Django database

---

install/basic/index.rst

Helps address "Is it Docker or DNS?" sources of Error 503 when moving from localhost to a domain name ("Deploy GeoNode on a production server").

Add step 6 to Troubleshooting

---

advanced/contrib/index.rst

~In conjunction with: https://github.com/GeoNode/geonode-contribs/pull/133~
Wrong. You shall set both env vars to false to switch group mirroring off.

added MIRROR_GROUPS as Env variable

---

advanced/contrib/index.rst

Provides a working logging setup for ldap contrib app inside the example settings.py snippet

Example of enabled logging for ldap

---

contribute/translation/index.rst

Changed the makemessage example to include `--no-location` according to https://github.com/GeoNode/geonode/pull/7019

new .po file structure without locations

---

install/advanced/core/index.rst

The ppa:ubuntugis/ppa repisitory does not support Ubuntu 20.04 focal, but ppa:ubuntugis/ubuntugis-unstable can. And ubuntu 20.04LTS does not need ppa:certbot/certbot.
#76

Fix installation ubuntu ppa

---

install/advanced/project/index.rst

This commit adds the missing information about how to setup PostgresQL when running the installation on Ubuntu 18.04 manually. 
This information was provided in previous versions of the documentation but seems to have been left out of the current version.

added information explaining how to install PostgresQL on Ubuntu 18.0.4

---

intermediate/backup/index.rst

Documentation update for introduction of `--soft-delete` in restore management command
Related issue: https://github.com/GeoNode/geonode/issues/7089
Related PR: https://github.com/GeoNode/geonode/pull/7090

[Relates to #7089] Delete existing table on restore

---

advanced/hardening/index.rst

I added the document for changing the default port of the geonode here. I am not sure in which section it should be included. But for now, I have added it under the geonode configuration > advance section. 
Please don't close issue #149. I will add the SSL installation section as well.

Docs for geonode on non-HTTP port

---

conf.py

Read the docs creates a PDF Version for generated docs. Unfortunately those pdf files contain a lot of empty pages. This added config will skip those

Remove empty pages

---

install/basic/index.rst

I added a simple warning tab to notify users that the variable GEOSERVER_ADMIN_PASSWORD configured in **.env** is not actually used to change the GeoServer admin password. I edited only this part of documentation because it is the only part where GEOSERVER_ADMIN_PASSWORD is explicitly mentioned inside the **.env** file and this is the variable that is used by geoserverfixture to try to reset admin password without success.

Update documentation about GeoServer admin password

---

install/advanced/core/index.rst

This adds the two env keys DATABASE_URL and GEODATABASE_URL to the minimum list of supervisor environment variables that are recommended in the docs. #173 
I also added a second commit that does a little bit of reorganizing that docs section, and adds an alternative syntax for the environment directive that I have found helpful. I can remake the PR without that second commit if that would be better.

173 add db settings to supervisor

---

admin/index.rst
admin/mgmt_commands/index.rst

improves #212 
- adds a section header introducing management commands
- adds some clarification for import and update-layers

some textual improvements on management commands

---

admin/index.rst
admin/mgmt_commands/index.rst
admin/thesaurus/index.rst

Also some polishing and fixing of a few typos on the rest of the thesaurus documentation and the addition of a couple of references to the command docs from the mgmt_commands page.
This is associated with GeoNode/geonode#8702

Add documentation for the dump_thesaurus command

---

devel/api/V2/schema/openapi.yml

Updates the following:
- use dataset(s) instead of layer(s)
- change url `api/v2/layers` to `api/v2/datasets`
- add missing apis
- remove geostories APIs

[Fixes #205] Update API v2 REST

---

install/advanced/core/index.rst

The command  `sudo update-java-alternatives --jre-headless --jre --set java-1.8.0-openjdk-amd64` results in the following error in Ubuntu 20.04LTS terminal. Therefore as a workaround, I used this command 
```
update-alternatives: error: no alternatives for policytool
update-alternatives: error: no alternatives for policytool
```
Therefore, using the command `sudo update-alternatives --config java` provides options for selecting default java as shown below.
```
There are 2 choices for the alternative java (providing /usr/bin/java).
Selection    Path                                            Priority   Status
------------------------------------------------------------
0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111      auto mode
1 …
```

Setting default java

---

install/advanced/project/index.rst

Update to various sections that include:
* Ubuntu 18.04 to Ubuntu 20.04
* Additional dependencies `ubuntugis/ppa`  with reference to issue #235 
* Installation of `libmemcachhe-dev` which without it brings issue of `pylibmc` missing..
* Setting default java via `update-alternatives --config` as the old/previous command shows the following:
* Correction to paths for files residing in [src](https://github.com/GeoNode/geonode-project/tree/master/src) folder
* Making the file `paver_dev.sh` executable.

[Fixes #238] Update to advanced installation for geonode-project

---

about/index.rst

The master docs still naming 3.2 this should be 4.0

Bump Version from 3.2 to 4.0

---

devel/api/V2/schema/openapi.yml
devel/api/integration/index.rst
requirements_docs.txt

* The dependency [m2r](https://github.com/miyakogi/m2r) is not maintained since a long time ago and now leads to a conflict. I changed the m2r dependency to it's still maintained [m2r2 ](https://github.com/CrossNox/m2r2) fork.
* The description for the API endpoint `PATCH api/vs/datasets/{id}` was written under `PUT`. I fixed the location and added an example. (I couldn't get the part underneath the moved one to work so that might be also wrong. But I didn't have time to investigate that)
* I added examples for how to get metadata and how to update them.

fix broken m2r dependency, fix wrong API description, added Example

---

install/advanced/core/docker/ubuntu.rst

According to the Ubuntu documentation, the use of apt-key is deprecated, except for the use of apt-key del in maintainer scripts to remove existing keys from the main key ring. Please refer to the below references for details.
* [Linux uprising article](https://www.linuxuprising.com/2021/01/apt-key-is-deprecated-how-to-add.html)
* [Unix stackexchange thread](https://unix.stackexchange.com/questions/332672/how-to-add-a-third-party-repo-and-key-in-debian/582853#582853)
Further, referring to [this docker documentation](https://docs.docker.com/engine/install/ubuntu/), it has changed from apt-key add to using **sudo gpg --dearmor -o** command

Docker GPG keys

---

admin/upgrade/3.2-to-3.3/index.rst
admin/upgrade/3.x-to-4.x/index.rst
admin/upgrade/index.rst

The PR includes a guide to upgrade from geonode 3.x to 4.x
It also has modifications to the index where documentation about the upgrades is compiled.
@anthieni @herver1971

Instructions for upgrading from 3.x to 4.x

---

start/index.rst

The current link, seems to be still pointing to a discontinued end point:
It is now updated to the correct end point:

Update demo link to point to stable build
